const S = (id) => `https://cdn.cloudflare.steamstatic.com/steam/apps/${id}/header.jpg`;
export const ALL_GAMES = [
  { title: "Baldur's Gate 3",             platform: "steam",       price: "$59.99", img: S(1086940), link: "https://store.steampowered.com/app/1086940/" },
  { title: "Counter-Strike 2",            platform: "steam",       price: "Free",   img: S(730),     link: "https://store.steampowered.com/app/730/" },
  { title: "Elden Ring",                  platform: "steam",       price: "$59.99", img: S(1245620), link: "https://store.steampowered.com/app/1245620/" },
  { title: "Hades II",                    platform: "steam",       price: "$29.99", img: S(1145350), link: "https://store.steampowered.com/app/1145350/" },
  { title: "Palworld",                    platform: "steam",       price: "$29.99", img: S(1623730), link: "https://store.steampowered.com/app/1623730/" },
  { title: "Helldivers 2",               platform: "steam",       price: "$39.99", img: S(553850),  link: "https://store.steampowered.com/app/553850/" },
  { title: "Lethal Company",              platform: "steam",       price: "$9.99",  img: S(1966720), link: "https://store.steampowered.com/app/1966720/" },
  { title: "Valheim",                     platform: "steam",       price: "$19.99", img: S(892970),  link: "https://store.steampowered.com/app/892970/" },
  { title: "Rust",                        platform: "steam",       price: "$39.99", img: S(252490),  link: "https://store.steampowered.com/app/252490/" },
  { title: "Terraria",                    platform: "steam",       price: "$9.99",  img: S(105600),  link: "https://store.steampowered.com/app/105600/" },
  { title: "GTA V",                       platform: "steam",       price: "$29.99", img: S(271590),  link: "https://store.steampowered.com/app/271590/" },
  { title: "Red Dead Redemption 2",       platform: "steam",       price: "$39.99", img: S(1174180), link: "https://store.steampowered.com/app/1174180/" },
  { title: "Cyberpunk 2077",              platform: "steam",       price: "$59.99", img: S(1091500), link: "https://store.steampowered.com/app/1091500/" },
  { title: "The Witcher 3",               platform: "steam",       price: "$14.99", img: S(292030),  link: "https://store.steampowered.com/app/292030/" },
  { title: "Stardew Valley",              platform: "steam",       price: "$14.99", img: S(413150),  link: "https://store.steampowered.com/app/413150/" },
  { title: "Dota 2",                      platform: "steam",       price: "Free",   img: S(570),     link: "https://store.steampowered.com/app/570/" },
  { title: "Apex Legends",                platform: "steam",       price: "Free",   img: S(1172470), link: "https://store.steampowered.com/app/1172470/" },
  { title: "Dark Souls III",              platform: "steam",       price: "$39.99", img: S(374320),  link: "https://store.steampowered.com/app/374320/" },
  { title: "Sekiro: Shadows Die Twice",   platform: "steam",       price: "$59.99", img: S(814380),  link: "https://store.steampowered.com/app/814380/" },
  { title: "Monster Hunter: World",       platform: "steam",       price: "$29.99", img: S(582010),  link: "https://store.steampowered.com/app/582010/" },
  { title: "Subnautica",                  platform: "steam",       price: "$29.99", img: S(264710),  link: "https://store.steampowered.com/app/264710/" },
  { title: "Deep Rock Galactic",          platform: "steam",       price: "$17.99", img: S(548430),  link: "https://store.steampowered.com/app/548430/" },
  { title: "V Rising",                    platform: "steam",       price: "$34.99", img: S(1604030), link: "https://store.steampowered.com/app/1604030/" },
  { title: "Satisfactory",                platform: "steam",       price: "$35.00", img: S(526870),  link: "https://store.steampowered.com/app/526870/" },
  { title: "RimWorld",                    platform: "steam",       price: "$34.99", img: S(294100),  link: "https://store.steampowered.com/app/294100/" },
  { title: "Crusader Kings III",          platform: "steam",       price: "$33.49", img: S(1158310), link: "https://store.steampowered.com/app/1158310/" },
  { title: "Team Fortress 2",             platform: "steam",       price: "Free",   img: S(440),     link: "https://store.steampowered.com/app/440/" },
  { title: "Left 4 Dead 2",              platform: "steam",       price: "$1.99",  img: S(550),     link: "https://store.steampowered.com/app/550/" },
  { title: "Warframe",                    platform: "steam",       price: "Free",   img: S(230410),  link: "https://store.steampowered.com/app/230410/" },
  { title: "Destiny 2",                   platform: "steam",       price: "Free",   img: S(1085660), link: "https://store.steampowered.com/app/1085660/" },
  { title: "Halo Infinite",               platform: "xbox",        price: "$59.99", img: S(1144200), link: "https://www.xbox.com/en-US/games/halo-infinite" },
  { title: "Forza Horizon 5",             platform: "xbox",        price: "$59.99", img: S(1551360), link: "https://www.xbox.com/en-US/games/forza-horizon-5" },
  { title: "Starfield",                   platform: "xbox",        price: "$69.99", img: S(1716740), link: "https://www.xbox.com/en-US/games/starfield" },
  { title: "Minecraft",                   platform: "xbox",        price: "$29.99", img: S(1828090), link: "https://www.xbox.com/en-US/games/minecraft" },
  { title: "Gears 5",                     platform: "xbox",        price: "$29.99", img: S(1097150), link: "https://www.xbox.com/en-US/games/gears-5" },
  { title: "Sea of Thieves",              platform: "xbox",        price: "$39.99", img: S(1172620), link: "https://www.xbox.com/en-US/games/sea-of-thieves" },
  { title: "Grounded",                    platform: "xbox",        price: "$29.99", img: S(962130),  link: "https://www.xbox.com/en-US/games/grounded" },
  { title: "Hi-Fi Rush",                  platform: "xbox",        price: "$29.99", img: S(1333550), link: "https://www.xbox.com/en-US/games/hi-fi-rush" },
  { title: "Avowed",                      platform: "xbox",        price: "$69.99", img: S(1716740), link: "https://www.xbox.com/en-US/games/avowed" },
  { title: "ASTRO BOT",                   platform: "playstation", price: "$59.99", img: S(1172470), link: "https://www.playstation.com/en-us/games/astro-bot/" },
  { title: "God of War Ragnarök",         platform: "playstation", price: "$59.99", img: S(1716740), link: "https://www.playstation.com/en-us/games/god-of-war-ragnarok/" },
  { title: "Marvel's Spider-Man 2",       platform: "playstation", price: "$69.99", img: S(1966720), link: "https://www.playstation.com/en-us/games/marvels-spider-man-2/" },
  { title: "Horizon Forbidden West",      platform: "playstation", price: "$59.99", img: S(1091500), link: "https://www.playstation.com/en-us/games/horizon-forbidden-west/" },
  { title: "The Last of Us Part I",       platform: "playstation", price: "$49.99", img: S(1174180), link: "https://www.playstation.com/en-us/games/the-last-of-us-part-i/" },
  { title: "Stellar Blade",               platform: "playstation", price: "$69.99", img: S(1841280), link: "https://www.playstation.com/en-us/games/stellar-blade/" },
  { title: "Ghost of Tsushima",           platform: "playstation", price: "$49.99", img: S(1250410), link: "https://www.playstation.com/en-us/games/ghost-of-tsushima-directors-cut/" },
  { title: "Returnal",                    platform: "playstation", price: "$49.99", img: S(1097150), link: "https://www.playstation.com/en-us/games/returnal/" },
  { title: "Bloodborne",                  platform: "playstation", price: "$19.99", img: S(374320),  link: "https://store.playstation.com/en-us/product/UP9000-CUSA00207_00-BLOODBORNE0000EU" },
  { title: "The Legend of Zelda: Tears of the Kingdom", platform: "nintendo", price: "$69.99", img: S(289070),  link: "https://www.nintendo.com/us/store/products/the-legend-of-zelda-tears-of-the-kingdom-switch/" },
  { title: "Super Mario Bros. Wonder",    platform: "nintendo",    price: "$59.99", img: S(105600),  link: "https://www.nintendo.com/us/store/products/super-mario-bros-wonder-switch/" },
  { title: "Mario Kart 8 Deluxe",         platform: "nintendo",    price: "$59.99", img: S(578080),  link: "https://www.nintendo.com/us/store/products/mario-kart-8-deluxe-switch/" },
  { title: "Animal Crossing: New Horizons", platform: "nintendo",  price: "$59.99", img: S(892970),  link: "https://www.nintendo.com/us/store/products/animal-crossing-new-horizons-switch/" },
  { title: "Super Smash Bros. Ultimate",  platform: "nintendo",    price: "$59.99", img: S(1145350), link: "https://www.nintendo.com/us/store/products/super-smash-bros-ultimate-switch/" },
  { title: "Splatoon 3",                  platform: "nintendo",    price: "$59.99", img: S(1623730), link: "https://www.nintendo.com/us/store/products/splatoon-3-switch/" },
  { title: "Pikmin 4",                    platform: "nintendo",    price: "$59.99", img: S(1841280), link: "https://www.nintendo.com/us/store/products/pikmin-4-switch/" },
  { title: "Hades",                       platform: "nintendo",    price: "$24.99", img: S(1145350), link: "https://www.nintendo.com/us/store/products/hades-switch/" },
  { title: "Celeste",                     platform: "nintendo",    price: "$19.99", img: S(1057090), link: "https://www.nintendo.com/us/store/products/celeste-switch/" },
  { title: "Hollow Knight: Silksong",     platform: "nintendo",    price: "$29.99", img: S(1172620), link: "https://www.nintendo.com/us/store/products/hollow-knight-silksong-switch/" },
];
